# Generated by Django 5.0.6 on 2024-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=250)),
                ('capacidad', models.IntegerField()),
                ('aire_acondicionado', models.BooleanField(default=True)),
                ('reclinable', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='servicios/imagenes/')),
            ],
        ),
    ]
